# Generated by Django 2.2.4 on 2019-12-12 01:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UekBasicStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='阶段编号')),
                ('stage_name', models.CharField(max_length=255, verbose_name='阶段名称')),
                ('dir_id', models.IntegerField(verbose_name='所属方向id')),
                ('stage_day', models.IntegerField(blank=True, null=True, verbose_name='阶段天数')),
                ('order_num', models.IntegerField(blank=True, null=True, verbose_name='阶段顺序')),
                ('stage_status', models.IntegerField(blank=True, help_text='0正常 1禁用', null=True, verbose_name='阶段状态')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '阶段表',
                'db_table': 'uek_basic_stage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UekBasicTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255, verbose_name='教师姓名')),
                ('teacher_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='教师工号')),
                ('dept_id', models.IntegerField(verbose_name='所属部门id')),
                ('dir_id', models.IntegerField(blank=True, null=True, verbose_name='方向id')),
                ('teacher_level', models.IntegerField(verbose_name='教师等级')),
                ('teacher_priority', models.CharField(blank=True, max_length=255, null=True, verbose_name='带课优先级')),
                ('teacher_status', models.IntegerField(blank=True, help_text='0 正常 1 请假', null=True, verbose_name='教师状态')),
                ('teacher_week_status', models.CharField(default='0000000', max_length=255, verbose_name='教师下周临时状态')),
                ('sex', models.IntegerField(help_text='1 男 2 女', verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('phone', models.CharField(max_length=255, verbose_name='手机号')),
                ('birthday', models.CharField(blank=True, max_length=255, null=True, verbose_name='出生年月')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='教师邮箱')),
                ('school', models.CharField(blank=True, max_length=255, null=True, verbose_name='毕业院校')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='毕业院校院系')),
                ('major', models.CharField(blank=True, max_length=255, null=True, verbose_name='毕业院校专业')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='学历')),
            ],
            options={
                'verbose_name_plural': '老师表',
                'db_table': 'uek_basic_teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UekCourseDayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField(blank=True, null=True, verbose_name='班级ID')),
                ('s_id', models.IntegerField(blank=True, null=True, verbose_name='阶段')),
                ('long_time', models.IntegerField(default=0, verbose_name='阶段已上课时')),
                ('week', models.IntegerField(default=0, verbose_name='第几周')),
                ('teacher', models.IntegerField(blank=True, null=True, verbose_name='教师id')),
                ('room', models.IntegerField(blank=True, null=True, verbose_name='教室')),
                ('daytime', models.CharField(blank=True, max_length=50, null=True, verbose_name='上课时间')),
                ('endstage', models.CharField(blank=True, max_length=50, null=True, verbose_name='完成阶段')),
            ],
            options={
                'verbose_name_plural': '班级每周信息',
                'db_table': 'uek_course_daydata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UekCourseOutClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班名')),
                ('croom', models.CharField(max_length=20, verbose_name='上课地点')),
                ('data', models.CharField(default='0|0|0|0|0|0|0', help_text='0代表该天无课', max_length=200, verbose_name='课程数据')),
                ('teacher', models.CharField(blank=True, default='0|0|0|0|0|0|0', help_text='0代表该天无老师', max_length=200, verbose_name='上课老师')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开班时间')),
            ],
            options={
                'verbose_name_plural': '校外班级表',
                'db_table': 'uek_course_outclasses',
            },
        ),
        migrations.CreateModel(
            name='UekCourseWeekData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=5000, verbose_name='课表数据')),
                ('week', models.IntegerField(default=0, verbose_name='周数')),
            ],
            options={
                'verbose_name_plural': '周课表数据',
                'db_table': 'uek_course_weekdata',
            },
        ),
        migrations.CreateModel(
            name='UekCourseTSPriorty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorty', models.IntegerField(blank=True, null=True, verbose_name='优先级')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseIndex.UekBasicStage', verbose_name='阶段')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseIndex.UekBasicTeacher', verbose_name='布道师')),
            ],
            options={
                'db_table': 'uek_course_tspriorty',
            },
        ),
        migrations.CreateModel(
            name='UekCourseStagePriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='优先级')),
                ('next_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_course', to='courseIndex.UekBasicStage', verbose_name='后续阶段')),
                ('pre_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_course', to='courseIndex.UekBasicStage', verbose_name='前导阶段')),
            ],
            options={
                'verbose_name_plural': '阶段优先级',
                'db_table': 'uek_course_stagepriority',
            },
        ),
    ]
